### PR TITLE
updated with new header and name

### PR DESCRIPTION
**Pull request by merraksh**
Upon suggestion from the new Chair, we've updated the name/header. 

PS Thanks for updating the .md, I'll add it to the TODO list for every new submission.

### CODE REVIEW

**Comment by merraksh** [comment]
Any news for this PR? We'd like to send the announcement to Engage with the link.

By the way, upstream/main has the new issue and the link, but  the website is not up to date yet.

**Comment by wildsm** [comment]
I was hoping the new officers would be taking this over (or the editors could manage), I'll merge in now.
I see that an email went out, but the [link I followed](https://siagoptimization.github.io/assets/views/ViewsAndNews-30-2.pdf)  404ed for me

**Comment by wildsm** [comment]
FYI- post merge (and time) https://siagoptimization.github.io/assets/views/ViewsAndNews-30-2.pdf now works for me

**Comment by wildsm** [comment]
Thanks all

**Comment by merraksh** [comment]
Thank you @wildsm. I'm happy to take over for now. I can see I'm a member of SIAGOptimization so I'll take care of merging future PRs.

**Pull request merged**
